platform:ios,'10.0'

target:'JL_OTA' do

pod 'Masonry'

pod 'AFNetworking'

pod 'Colours'

pod 'MJRefresh'

pod 'GCDWebServer/WebUploader'

pod 'GCDWebServer/WebDAV'

pod 'GCDWebServer'

pod 'Bugly'

end

